=== Gasparrabadantoro/Publico/2ndotrimestre/OyeComoVa.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="cancion">
        <xs:complexType mixed="true">
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="autor"/>
                <xs:element ref="interprete"/>
                <xs:element ref="letra"/>
                <xs:element ref="titulo"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="autor" type="xs:string"/>
    <xs:element name="interprete" type="xs:string"/>
    <xs:element name="letra">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="tipo"/>
                <xs:element ref="estrofa"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="estrofa">
        <xs:complexType mixed="true">
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="tipo"/>
                <xs:element ref="orden"/>
                <xs:element ref="verso"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="orden" type="xs:integer"/>
    <xs:element name="verso" type="xs:string"/>
    <xs:element name="titulo" type="xs:string"/>
    <xs:element name="tipo" type="xs:NCName"/>
</xs:schema>

=== Gasparrabadantoro/Publico/2ndotrimestre/OyeComoVa.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="OyeComoVa.xsl"?>

<cancion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/xampp/htdocs/OyeComoVa/OyeComoVa.xsd">
	<titulo>Oye como va</titulo>
	<autor>Tito Puente </autor>
	<interprete>Celia Cruz </interprete>
	<letra>
		
	<estrofa>
		
		<tipo>estribillo</tipo>
		<orden>1</orden>
		<verso><span>
			 Oye como va, mi ritmo
		</span>
			 
		</verso>
		Bueno pa' goza', mulata
			<verso>
			Oye como va, mi ritmo
			</verso>
				<verso>
					Bueno pa' goza', mulata
				</verso>
					
						
	</estrofa>
	
	
	<estrofa >-2
		<tipo>normal</tipo>
		<orden>2</orden>
			<verso>Si tú no sabes bailar
				
			</verso>
				<verso>
					Si estás peleado con el son
				</verso>
					<verso>
						Sígueme marcando el paso
					</verso>
						<verso>
						Que te aseguro que es de lo más sabrosón
						</verso>
							
	</estrofa>
	<tipo>normal</tipo>
	<estrofa >
		<orden>3</orden>
			<verso>
			Voy pa' la rumba, la rumba, la rumba
			</verso>
				<verso>
				Porque me llama, me llama, me llama
				</verso>
					<verso>
						Y necesito que suene el coro
					</verso>
						<verso>
							Para que se ponga a vacilar
						</verso>
							
	</estrofa>
	<tipo>estribillo</tipo>
	<estrofa >
		<orden>4</orden>
			<verso>
				Oye como va, mi ritmo
			</verso>
				<verso>
				Bueno pa' goza', mulata

				</verso>
				Oye como ya, mi ritmo
					<verso>
						Bueno pa' goza', mulata
					</verso>

	</estrofa>
	<estrofa>
			<orden>5</orden>
			<tipo>estribillo</tipo>
		<verso>
		Esto se pone caliente
		</verso>
		<verso>
		Esto se baila apretado
		</verso>
		<verso>
		Cuatro pasitos pa'l frente
		</verso>
		<verso>
			Y un meneíto de lao
		</verso>
		
	</estrofa>
	
	</letra>/letra>
</cancion>
